name: Standard Issue 
description: Use this template for issues regarding one of the files in the folder `Code` or the .xlsm file
body:
  - type: markdown
    attributes:
      value: | 
        Any additions, changes or removals is at the Authors discretion. 
        You're free to counterargue (to a certain point) if you disagree with the decision. 
        To avoid being banned, don't constantly re-open or create new (related) issue reports

- type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I performed a cursory search of the issue tracker to avoid opening a duplicate issue
          required: true
        - label: This is **NOT** a question `-- use [this template](https://github.com/JohnyP36/VBA-Calendar/issues/new?assignees=&labels=question&template=questions.yml) for questions`
          required: true
        - label: I've read the [Code of Conduct](https://github.com/JohnyP36/VBA-Calendar/blob/main/.github/CODE_OF_CONDUCT.md) and the [Contributing Guidelines](https://github.com/JohnyP36/VBA-Calendar/blob/main/.github/CONTRIBUTING.md)
          required: true
        - label: This issue occured after I changed your code
          required: false

- type: checkboxes
    id: name2
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: I put the code in a clean, new Excel files
          required: true
        - label: other VBA *(other than the code in this repo)* on the same worksheet are disabled  -- `*This is to ensure there are no issues or conflicts with other code*`
          required: true
   
  - type: input
    attributes: 
      label: Office version
      placeholder: e.g. Office 2019, version 2112 (build 14729.20260) for Students and Home use
    validations:
      required: true
    
  - type: input
    attributes: 
      label: Operating System & Version
      placeholder: e.g. Windows 10, 21H2
    validations:
      required: true 
      
  - type: textarea
    attributes:
      label: Screenshot(s)
      description: |
        Screenshot(s) for difficult to describe visual issues are **mandatory**. 
        Post **links** instead of inline images for screenshots containing **Adult material**.
      value: | 
        <details>
        <summary>Screenshot 1</summary>
        
        <!-- drag-and-drop screenshot here -->
        
        </details>
    validations:
      required: false
